#-----------------------------------
--- # Application
#-----------------------------------

server:
  port: 8080

#-----------------------------------
--- # Authentication
#-----------------------------------

application:
  security:
    uuid: b592691e-df3f-4049-86d5-50bdce269354
    strength: 8
    system-username: SYSTEM
    system-password: $2a$16$Pjg5ZRu.I2TsN5W38PMyQuYBorSrwmRKa/4fc01nEZl0FSOQeou3C # SYSADM

#-----------------------------------
--- # Database
#-----------------------------------

spring:
  datasource:
    url: jdbc:postgresql://database:5432/_core
    username: admin
    password: $$TF123.asdu$123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#-----------------------------------
--- # i18n & L10n
#-----------------------------------

spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages

#-----------------------------------
--- # Logging
#-----------------------------------

logging:
  level:
    com:
      tujuhsembilan: TRACE

#-----------------------------------
--- # Miscellanous
#-----------------------------------

spring:
  output:
    ansi:
      enabled: always # Just console color, I'm lovin' it!

# # -----------------------------------
# --- #
# # -----------------------------------
